root: true

parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  es6: true
  node: true

plugins:
  - import
  - prettier

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - prettier

rules:
  eqeqeq: 0
  no-console: 0
  no-eq-null: 0
  no-negated-condition: 0
  no-unused-vars:
    - error
    - args: after-used
      argsIgnorePattern: "^_"
  no-var: error
  import/no-extraneous-dependencies: error
  prettier/prettier: error
  react/prop-types: off
  react/display-name: off
  react/no-children-prop: off
  react/react-in-jsx-scope: off

settings:
  react:
    version: 16.10.1

overrides:
  - files: "*.md"
    extends: plugin:mdx/recommended

  - files: "*.mdx"
    extends:
      - plugin:mdx/recommended
      - plugin:mdx/overrides
    rules:
      import/no-extraneous-dependencies: 0

  - files:
      - "**/test/**/*.js"
      - "**/*.test.js"
    env:
      jest: true

  - files:
      - "src/**/*js"
    env:
      browser: true
    rules:
      import/default: 0
      import/namespace: 0
      import/named: 0
      import/no-default-export: 0
      import/no-extraneous-dependencies: off
      import/no-unresolved: off
      no-unused-vars: 0
